on: push
name: Development Deploy workflow

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=.next --prod --auth=${{ env.NETLIFY_AUTH_TOKEN }} --site=${{env.NETLIFY_SITE_ID}}
      - run: echo 'NETLIFY_AUTH_TOKEN- ${{ env.NETLIFY_AUTH_TOKEN }}'
      - run: echo 'NETLIFY_SITE_ID- ${{ env.NETLIFY_SITE_ID }}'